image: maven:3-jdk-8
deploy:
  script:
    - 'mvn deploy -s ci_settings.xml'
  only:
    - master
build:
  script: "mvn clean package"
  artifacts:
    name: "ItemMods"
    paths: 
    - "target/*.jar"
pages:
  script:
    - 'mvn javadoc:javadoc'
  only:
    - master