site_name: ItemMods
site_url: https://codedoctorde.github.io/itemmods/index.html
repo_url: https://github.com/codedoctorde/itemmods/
theme: material
markdown_extensions:
  - codehilite
nav:
  - Home: README.md