site_name: ItemMods
site_url: https://codedoctorde.gitlab.io/itemmods
repo_url: https://gitlab.com/codedoctorde/itemmods/
theme: material
markdown_extensions:
  - codehilite:
      linenums: true
nav:
  - Home: README.md
  - "Items":
      - "Create items": create-item.md
      - "Create custom items": create-custom-item.md