name: ItemMods
author: CodeDoctorDE
version: 1.1.6
load: STARTUP
api-version: "1.13"
main: com.gitlab.codedoctorde.itemmods.main.Main
commands:
  itemmods:
    aliases:
      - itemmods
      - itemmod
      - itemm
      - imods
      - imod
      - im
      - ims
    usage: "\u00a74Usage: \u00a73/itemmods\u00a74!"
