# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package
      - uses: actions/upload-artifact@v1
        with:
          name: "ItemMods.jar"
          path: "target/ItemMods.jar"
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://openkbs/jdk-mvn-py3:1.2.2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: "Install mkdocs"
        run: |
          sudo pip install mkdocs-material
      - name: "Build pages"
        run: |
          mv assets docs
          mv ./*.md docs
          mkdocs build
          mkdir public
          mv site/* public
          mvn javadoc:javadoc
          mv target/site/* public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public